### ISSUE TITLE
ioredis Cluster support?

### ISSUE THREAD

**Issue by wjhsf** [natesilva/keyv-anyredis#1]
Per the [README](https://github.com/natesilva/keyv-anyredis/blob/v1.1.0/README.md#background):
> While this covers many use cases, it doesn’t work for the following:
> - Using ioredis in cluster mode.

But ioredis [Clusters](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0a547a751d5f6a9d869863c055f6a762501936b/types/ioredis/index.d.ts#L1669) implements the [`CompatibleRedisClient`](https://github.com/natesilva/keyv-anyredis/blob/c00e430325af7d39f34dec545d6d08165471b5a3/src/compatible-redis-client.ts#L55) interface, so why is cluster mode not supported?

**Comment by natesilva** [comment]
It does implement that, but:

* at https://github.com/lukechilds/keyv-redis/blob/9d650f21ce4609c07d5e6848efb1572eccf95d46/src/index.js#L10 it checks for `instanceof Redis` which is not the same as `instanceof Redis.Cluster`
* at https://github.com/lukechilds/keyv-redis/blob/9d650f21ce4609c07d5e6848efb1572eccf95d46/src/index.js#L61 it bulk-deletes keys, which doesn’t work in cluster (you can only bulk-delete keys that are in the same cluster slot)

These are relatively easy to fix in the official client, but there’s no need to take the approach that everyone will be using ioredis since it’s relatively easy to support a wider range of clients, so I made this.

**Comment by wjhsf** [comment]
That's why `@keyv/redis` doesn't support cluster mode. `keyv-anyredis` doesn't seem to use `@keyv/redis`, so why doesn't `keyv-anyredis` support cluster mode?

**Comment by natesilva** [comment]
`keyv-anyredis` definitely does support cluster mode. I guess I miscommunicated! I will update the README to be clearer.

**Comment by natesilva** [comment]
Updated the README to hopefully be more clear. Thank you!
